=== SaiPranav2974/IWP-DA-3/DA-3/2/food_order.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="food_order">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="customer" type="customerType"/>
                <xs:element name="items" type="itemsType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:complexType name="customerType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="address" type="xs:string"/>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="itemsType">
        <xs:sequence>
            <xs:element name="item" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="name" type="xs:string"/>
                        <xs:element name="quantity" type="xs:int"/>
                        <xs:element name="price" type="xs:decimal"/>
                    </xs:sequence>
                    <xs:attribute name="id" type="xs:string" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== SaiPranav2974/IWP-DA-3/DA-3/2/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="food_order.xsl"?>
<food_order xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="food_order.xsd">
    <customer>
        <name>John Doe</name>
        <address>123 Main St, City, Country</address>
        <email>john@example.com</email>
    </customer>
    <items>
        <item id="1">
            <name>Chicken Burger</name>
            <quantity>2</quantity>
            <price>250</price>
        </item>
        <item id="2">
            <name>Pizza</name>
            <quantity>1</quantity>
            <price>400</price>
        </item>
        <item id="3">
            <name>Biriyani</name>
            <quantity>1</quantity>
            <price>700</price>
        </item>
        <item id="4">
            <name>Meals</name>
            <quantity>3</quantity>
            <price>1000</price>
        </item>
    </items>
</food_order>
